# Generated by Django 3.0.8 on 2020-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.CharField(max_length=100)),
                ('Amount', models.FloatField(max_length=20)),
                ('MpesaReceiptNumber', models.CharField(max_length=20)),
                ('Balance', models.CharField(blank=True, max_length=20, null=True)),
                ('TransactionDate', models.DateTimeField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Lipa na MPESA',
                'verbose_name_plural': 'Lipa na MPESA',
                'db_table': 'payments_lipanampesa',
                'ordering': ['-TransactionDate'],
            },
        ),
    ]
