# Generated by Django 3.0.8 on 2020-07-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default='No content yet...'),
        ),
    ]
